// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classespackage;

/************************************************************/
/**
 * 
 */
public class Biglietto {
	/**
	 * 
	 */
	private int idBiglietto;
	/**
	 * 
	 */
	public String nomeUtilizzatore;
	/**
	 * 
	 */
	private String cognomeUtilizzatore;
	/**
	 * 
	 */
	public Posto posto;
	/**
	 * 
	 */
	public Utente utente;
}
