// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classespackage;

/************************************************************/
/**
 * 
 */
public abstract class Evento {
	/**
	 * 
	 */
	private int idEvento;
	/**
	 * 
	 */
	private String nome;
	/**
	 * 
	 */
	private String data;
	/**
	 * 
	 */
	private String ora;
	/**
	 * 
	 */
	public Luogo luogo;
}
