// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classespackage;

/************************************************************/
/**
 * 
 */
public class EventoStadio extends Evento {
}
