// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classespackage;

/************************************************************/
/**
 * 
 */
public class Luogo {
	/**
	 * 
	 */
	private int idLuogo;
	/**
	 * 
	 */
	private String nome;
	/**
	 * 
	 */
	private String indirizzo;
}
