// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classespackage;

/************************************************************/
/**
 * 
 */
public class Posto {
	/**
	 * 
	 */
	private int idPosto;
	/**
	 * 
	 */
	private int num;
	/**
	 * 
	 */
	public Settore settore;
}
