// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classespackage;

/************************************************************/
/**
 * 
 */
public class Settore {
	/**
	 * 
	 */
	private int idSettore;
	/**
	 * 
	 */
	private String nome;
	/**
	 * 
	 */
	private float prezzo;
	/**
	 * 
	 */
	private int postiTotali;
	/**
	 * 
	 */
	public int postiOccupati;
	/**
	 * 
	 */
	public Evento evento;
}
